---
# tasks file for open-build-service
- name: Configure Open Build Service repository
  zypper_repository:
    name: "OBS_{{obs_version}}"
    repo: "https://download.opensuse.org/repositories/OBS:/Server:/{{obs_version}}/openSUSE_{{obs_opensuse_version}}/"
    auto_import_keys: yes
- name: Install Open Build Service pattern
  zypper:
    name: OBS_Server
    type: pattern
- name: Set up signer
  include_tasks: signer.yml
- name: Enable required backend services
  service:
    name: "{{ item }}"
    enabled: yes
    state: started
  loop:
    - obsrepserver
    - obssrcserver
    - obsscheduler
    - obsdispatcher
    - obspublisher
- name: Enable recommended backend services
  service:
    name: "{{ item }}"
    enabled: yes
    state: started
  loop:
    - obsdodup
    - obsdeltastore
    - obssigner
    - obssignd
    - obsservicedispatch
- name: Enable optional backend services
  service:
    name: "{{ item }}"
    enabled: yes
    state: started
  loop:
    - obswarden
    - obsapisetup
    - obsstoragesetup
    - obsworker
    - obsservice
- name: Enable MySQL
  service:
    name: mysql
    enabled: yes
    state: started
