# Copyright (c) 2021, AT&T Intellectual Property.
#
# SPDX-License-Identifier: BSD-3-Clause
---
- name: Open HTTPS in the firewall
  firewalld:
    service: https
    immediate: yes
    permanent: yes
    state: enabled
- name: Open port 82 in the firewall
  firewalld:
    port: 82/tcp
    immediate: yes
    permanent: yes
    state: enabled
- name: Open port 5152 in the firewall for workers
  firewalld:
    port: 5152/tcp
    immediate: yes
    permanent: yes
    state: enabled
- name: Open port 5252 in the firewall for workers
  firewalld:
    port: 5252/tcp
    immediate: yes
    permanent: yes
    state: enabled
- name: Open port 5352 in the firewall for workers
  firewalld:
    port: 5352/tcp
    immediate: yes
    permanent: yes
    state: enabled
