# Copyright (c) 2020, AT&T Intellectual Property.
#
# SPDX-License-Identifier: BSD-3-Clause
---
# Install tasks for either server or worker or both
- name: Gather OBS version specific variables
  include_vars: "obs_{{obs_version}}.yml"
- name: Configure Open Build Service repository
  zypper_repository:
    name: "OBS_{{obs_version}}"
    repo: "https://download.opensuse.org/repositories/OBS:/Server:/{{obs_version}}/{{obs_opensuse_version}}/"
    auto_import_keys: yes
- name: Install Server
  include_tasks: server.yml
  when: install_server
- name: Install Worker
  include_tasks: worker.yml
  when: install_worker
- name: Set ownership on OBS directory
  file:
    path: /srv/obs
    owner: obsrun
    group: obsrun
    state: directory
