---
- name: Install Open Build Service Worker
  zypper:
    name: "{{ item }}"
    state: present
  loop:
    - kernel-obs-build
    - obs-common
    - obs-worker
- name: Setup the worker buildhost.config
  template:
    src: buildhost.config.j2
    dest: /etc/buildhost.config
    owner: root
    group: root
    mode: 0600
- name: Enable local build workers
  service:
    name: obsworker
    enabled: yes
    state: started
