# Copyright (c) 2020, AT&T Intellectual Property.
#
# SPDX-License-Identifier: BSD-3-Clause
---
# handlers file for open-build-service
- name: reload obssrcserver
  service:
    name: obssrcserver
    state: reloaded
- name: reload obsrepserver
  service:
    name: obsrepserver
    state: reloaded
- name: restart mysql
  service:
    name: mysql
    state: restarted
- name: restart obsscheduler
  service:
    name: obsscheduler
    state: restarted
- name: update ca certificates
  command: update-ca-certificates
- name: restart apache2
  service:
    name: apache2
    state: restarted
- name: reboot
  reboot:
