---
# handlers file for open-build-service
- name: reload obssrcserver
  service:
    name: obssrcserver
    state: reloaded
- name: reload obsrepserver
  service:
    name: obsrepserver
    state: reloaded
- name: restart mysql
  service:
    name: mysql
    state: restarted
- name: restart obsscheduler
  service:
    name: obsscheduler
    state: restarted
